version: "3.9"
name: mvc-thymeleaf
services:
  backend:
    container_name: mvc_thymeleaf_backend
    build:
      context: .
      dockerfile: dockerfile
    image: mvc_thymeleaf_backend
    env_file: .env
    ports:
      - ${HOST_PORT}:${APP_PORT}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_APP_PORT=${APP_PORT}
    networks:
      - mvc-network
    depends_on:
      - postgres


  postgres:
    container_name: mvc_thymeleaf_postgres
    image: postgres:12.5
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - mvc-network
#    ports:
#      - "5432:5432"


volumes:
  pg-data:

networks:
  mvc-network:
    driver: bridge