version: "3.9"
name: mvc
services:
  backend:
    container_name: backend_mvc_thymeleaf
    build:
      context: .
      dockerfile: dockerfile
    image: backend_mvc_thymeleaf
    ports:
      - "${HOST_PORT:-80}:${SPRING_APP_PORT:-8080}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - mvc-network
    depends_on:
      - postgres


  postgres:
    container_name: postgres_mvc_thymeleaf
    image: postgres:12.5
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - mvc-network
#    ports:
#      - "5432:5432"


volumes:
  pg-data:

networks:
  mvc-network:
    driver: bridge