server:
  port: 8080
spring:
  sql:
    init:
      mode: always
  application:
    name: spring-mvc-homework
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
